AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Cognito for Book DEPOT API app authentication

Resources:
  BookDepotAPIAppUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      UserPoolAddOns:
        AdvancedSecurityMode: AUDIT
      UserPoolName: BookDepot

  BookDepotAPIAppUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: bookdepot-api-userpool
      UserPoolId: !Ref BookDepotAPIAppUserPool

  BookDepotAPIResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      Identifier: InventoryAPI
      Name: InventoryAPI
      Scopes:
        - ScopeDescription: readonly access to Inventory API
          ScopeName: read
      UserPoolId: !Ref BookDepotAPIAppUserPool

  BookDepotAPIAppReadWritePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "cognito-idp:DescribeUserPoolClient"
              - "cognito-idp:CreateUserPoolClient"
            Resource:
              - !GetAtt BookDepotAPIAppUserPool.Arn

Outputs:
  UserPoolArn:
    Description: CognitoPool ARN
    Value: !GetAtt BookDepotAPIAppUserPool.Arn
    Export:
      Name: BookDepotAPIUserPoolArn

  UserPoolUrl:
    Description: CognitoPool Url
    Value: !Ref BookDepotAPIAppUserPoolDomain
    Export:
      Name: BookDepotAPIUserPoolUrl

  UserPoolId:
    Description: CognitoPool Id
    Value: !Ref BookDepotAPIAppUserPool
    Export:
      Name: BookDepotAPIUserPoolId

  CognitoReadWritePolicy:
    Description: Cognito read and write policy
    Value: !Ref BookDepotAPIAppReadWritePolicy
    Export:
      Name: BookDepotPICognitoReadWritePolicy
